import type { NewsItem, TradingConfig, SentimentData } from './types/news';

export const mock_news_items: NewsItem[] = [
    {
        _id: '1',
        title: 'BBG',
        body: 'COINBASE ANNOUNCES STOCK TRADING THROUGH ITS APP - Major expansion into traditional finance as crypto exchange diversifies offerings',
        time: Date.now() - 1000 * 60 * 5,
        icon: 'https://i.ibb.co/QH545y9/blog.png',
        link: 'https://bloomberg.com/news/coinbase-stock-trading',
        scrapedTime: Date.now() - 1000 * 60 * 5 + 100,
        type: 'news',
        image: 'https://picsum.photos/id/1/800/450',
        coins: ['BTC', 'ETH'],
    },
    {
        _id: '2',
        title: 'CZ (@CZ) [BINANCE SQUARE]',
        body: 'Exciting developments coming to Binance next week. Stay tuned for the official announcement.',
        time: Date.now() - 1000 * 60 * 12,
        icon: 'https://public.bnbstatic.com/image/pgc/202310/0e45b26df93791c33cd6c3b0b922074d.jpg',
        link: 'https://www.binance.com/en/square/post/33871550908074',
        scrapedTime: Date.now() - 1000 * 60 * 12 + 150,
        type: 'twitter',
        image: 'https://picsum.photos/id/48/600/600',
        coins: ['BNB'],
        info: {
            binanceUid: null,
            squareUid: 'dxCeCLOM7uOFJKX8EnS3Kw',
            isReply: false,
            isRetweet: false,
            isQuote: false,
            isSelfReply: false,
            isArticle: false,
            authorVerificationType: 1,
            isTranslated: false,
            originalLanguage: 'en',
        },
    },
    {
        _id: '3',
        title: 'Vitalik.eth (@vitalik) [BINANCE SQUARE]',
        body: 'This is huge! Congrats to the entire team. Years of work finally paying off.',
        time: Date.now() - 1000 * 60 * 25,
        icon: 'https://pbs.twimg.com/profile_images/977496875887558661/L86xyLF4_400x400.jpg',
        link: 'https://www.binance.com/en/square/post/44445550908999',
        scrapedTime: Date.now() - 1000 * 60 * 25 + 200,
        type: 'twitter',
        image: 'https://picsum.photos/id/119/500/350',
        coins: ['ETH'],
        info: {
            binanceUid: '12345678',
            squareUid: 'vitalik_square_uid',
            isReply: false,
            isRetweet: true,
            isQuote: false,
            isSelfReply: false,
            isArticle: false,
            authorVerificationType: 2,
            isTranslated: false,
            originalLanguage: 'en',
            embedded_tweet: {
                id: 'eth_merge_tweet_001',
                text: 'The merge is complete. Ethereum is now proof of stake. https://ethereum.org/en/roadmap/merge/',
                author_name: 'Ethereum',
                author_handle: 'ethereum',
                author_avatar: 'https://pbs.twimg.com/profile_images/1729585600747192320/xQY3DjSZ_400x400.jpg',
                created_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
                link: 'https://twitter.com/ethereum/status/1234567890',
            },
        },
    },
    {
        _id: '4',
        title: 'BWE Alert',
        body: 'Price Monitor: BTCUSDT +3.2% in the past 60 seconds. Unusual volume detected.',
        time: Date.now() - 1000 * 60 * 40,
        icon: 'https://i.ibb.co/LdQt0DH/3be9703b-9c93-48cb-a6f0-52396cb523a6.jpg',
        link: 'https://www.binance.com?time=1766049114625',
        scrapedTime: Date.now() - 1000 * 60 * 40 + 58,
        type: 'alert',
        image: 'https://picsum.photos/id/160/400/650',
        coins: ['BTC'],
    },
    {
        _id: '5',
        title: 'Market commentary (@Lucky) [DC]',
        body: 'Just spotted this - the Hyperliquid whale added significantly to their ETH long position. Currently down $61m but actively adding. Check it out: https://hyperliquid.xyz/explorer',
        time: Date.now() - 1000 * 60 * 55,
        icon: 'https://cdn.discordapp.com/avatars/1088048323430187041/02b22749775ca72382c6bb29c2cce8a9.webp',
        link: 'https://discord.com/channels/1181197353827434516/1372546055362707526/1451104349689348178',
        scrapedTime: Date.now() - 1000 * 60 * 55 + 384,
        type: 'discord',
        image: 'https://picsum.photos/id/26/450/800',
        coins: ['ETH', 'BTC', 'SOL'],
    },
    {
        _id: '6',
        title: 'CryptoTrader (@trader_mike) [BINANCE SQUARE]',
        body: 'This chart is insane. Called it last week.',
        time: Date.now() - 1000 * 60 * 70,
        icon: 'https://pbs.twimg.com/profile_images/1234567890/trader_400x400.jpg',
        link: 'https://www.binance.com/en/square/post/55556660909222',
        scrapedTime: Date.now() - 1000 * 60 * 70 + 250,
        type: 'twitter',
        coins: ['BTC', 'DOGE'],
        info: {
            binanceUid: '99887766',
            squareUid: 'trader_mike_uid',
            isReply: false,
            isRetweet: true,
            isQuote: false,
            isSelfReply: false,
            isArticle: false,
            authorVerificationType: 1,
            isTranslated: false,
            originalLanguage: 'en',
            embedded_tweet: {
                id: 'btc_chart_tweet_001',
                text: 'BTC breaking out of the ascending triangle. Target: $120k by end of Q1. Not financial advice.',
                author_name: 'Bitcoin Magazine',
                author_handle: 'BitcoinMagazine',
                author_avatar: 'https://pbs.twimg.com/profile_images/bitcoin_mag/avatar.jpg',
                created_at: new Date(Date.now() - 1000 * 60 * 75).toISOString(),
                link: 'https://twitter.com/BitcoinMagazine/status/9876543210',
                image: 'https://picsum.photos/id/60/800/500',
            },
        },
    },
];

export const mock_trading_config: TradingConfig = {
    enabled: true,
    coins: [
        { symbol: 'BTC', name: 'Bitcoin', enabled: true },
        { symbol: 'ETH', name: 'Ethereum', enabled: true },
        { symbol: 'SOL', name: 'Solana', enabled: true },
    ],
    preset_amounts: [100, 250, 500, 1000],
};

export const mock_sentiment_data: SentimentData[] = [
    { news_id: '1', sentiment: 'positive' },
    { news_id: '2', sentiment: 'neutral' },
    { news_id: '3', sentiment: 'positive' },
    { news_id: '4', sentiment: 'positive' },
    { news_id: '5', sentiment: 'negative' },
    { news_id: '6', sentiment: 'positive' },
];
